# https://www.kernel.org/doc/html/latest/process/maintainer-pgp-guide.html
# gpg --list-keys "Jan van den Berg <koozz@linux.com>"
# FPR=""
# gpg --quick-add-key "${FPR}" cv25519 encr 0
# gpg --quick-add-key "${FPR}" ed25519 auth 0
# gpg --quick-add-key "${FPR}" ed25519 sign 0
# gpg --list-keys "Jan van den Berg <koozz@linux.com>"
# gpg -K --with-keygrip | grep -A1 "ed25519.*\[A\]"
# echo __keygrip__ >> ~/.gnupg/sshcontrol
# gpg --output public.pgp --armor --export koozz@linux.com

# auto-key-retrieval using WKD and DANE
auto-key-locate wkd,dane,local
auto-key-retrieve

# Trust on First Use (TOFU)
trust-model tofu+pgp
