#!/bin/bash
# vim:ft=bash ts=2 sw=2 sts=2 fenc=utf-8
set -euo pipefail

# Download Orca source
curl -sLo /tmp/orca.c https://wiki.xxiivv.com/src/inc/text/orca.c.txt

# Compile to $HOME/.bin/orca
cc -std=c89 -O2 -DNDEBUG -g0 -s -Wall -L/usr/local/lib -lSDL2 -lportmidi /tmp/orca.c -o "$HOME/.bin/orca"
