#!/bin/bash
# vim:ft=bash ts=2 sw=2 sts=2 fenc=utf-8
set -euo pipefail

if [[ -x "$(command -v pacman)" ]]; then
	# Refresh pacman
	sudo pacman -Syu --noconfirm

	# Refresh AUR
	if [[ -x "$(command -v yay)" ]]; then
		yay -Syu --noconfirm
	fi
fi
