#!/bin/bash
# vim:ft=bash ts=2 sw=2 sts=2 fenc=utf-8
set -euo pipefail

# Install GitHub cli here
GHCLI="$HOME/.bin/gh"

# Version online
URL="https://github.com/cli/cli/releases"
GHVERSION="$(curl --head -s "${URL}/latest" | grep -i "^Location:" | grep -oe '[[:digit:]]*\.[[:digit:]]*\.[[:digit:]]*')"

# Install if it's not the current version
if [[ ! $($GHCLI --version) =~ $GHVERSION ]]; then
	VERSIONURL="${URL}/download/v${GHVERSION}/gh_${GHVERSION}_linux_amd64.tar.gz"
	(cd "$(mktemp -d)" && curl -sSL "$VERSIONURL" | tar -xz && mv gh_${GHVERSION}_linux_amd64/bin/gh "$GHCLI")
	echo "Reconciled GitHub cli $GHVERSION."
else
	echo "Already have GitHub cli $GHVERSION."
fi
"${GHCLI}" completion -s zsh > "$HOME/.config/zsh/completions/_gh"
