#!/bin/bash
# vim:ft=bash ts=2 sw=2 sts=2 fenc=utf-8
set -euo pipefail

# Install velero here
VELERO="$HOME/.bin/velero"

# Version online
URL="https://github.com/vmware-tanzu/velero/releases"
VELEROVERSION="$(curl --head -s "${URL}/latest" | grep -i "^Location:" | grep -oe 'v[[:digit:]]*\.[[:digit:]]*\.[[:digit:]]*')"

# Get the current version
VELEROCURRENT=""
if [[ -x "$VELERO" ]]; then
	VELEROCURRENT=$($VELERO version --client-only | grep -oe 'v[[:digit:]]*\.[[:digit:]]*\.[[:digit:]]*')
fi

# Install if not the required version
if [[ "$VELEROCURRENT" != "$VELEROVERSION" ]]; then
	echo "Reconciling velero from $VELEROCURRENT to $VELEROVERSION"
	TMP="/tmp/velero-${VELEROVERSION}-linux-amd64"
	curl -sfLo ${TMP}.tar.gz "${URL}/download/$VELEROVERSION/velero-$VELEROVERSION-linux-amd64.tar.gz"
	mkdir -p "${TMP}"
	tar xzf "${TMP}.tar.gz" -C ${TMP} --strip-components=1
	mv ${TMP}/velero "$VELERO"
	rm -Rf ${TMP}*
else
	echo "Velero already at version: $VELEROVERSION."
fi
