#!/bin/bash
# vim:ft=bash ts=2 sw=2 sts=2 fenc=utf-8
set -euo pipefail

# Walk all subscriptions and merge aks credentials into kubeconfig
for subscription_id in $(az account list -o tsv --query "[].id"); do
	subscription=$(az account show --subscription "$subscription_id" -o tsv --query "name")
	echo "▼ Processing subscription $subscription"
	while read -r name group fqdn; do
		# Could even suffix with: -aks
		context="${fqdn%\-*\.*}"
		az aks get-credentials --subscription "$subscription" -n "$name" -g "$group" --context "$context" --overwrite-existing
	done < <(az aks list --subscription "$subscription" -o tsv --query "[].[name, resourceGroup, fqdn]")
done
