initial_screen = "library"
library_tabs = ["playlists", "artists", "albums", "tracks", "browse"]
repeat = "off"
shuffle = false
use_nerdfont = false

# [theme]
# background = "black"
# primary = "light white"
# secondary = "light black"
# title = "green"
# playing = "green"
# playing_selected = "light green"
# playing_bg = "black"
# highlight = "light white"
# highlight_bg = "#484848"
# error = "light white"
# error_bg = "red"
# statusbar = "black"
# statusbar_progress = "green"
# statusbar_bg = "green"
# cmdline = "light white"
# cmdline_bg = "black"
# search_match = "light red"
#
# [theme]
# background = "#313244"
# primary = "#cdd6f4"
# secondary = "#94e2d5"
# title = "#a6e3a1"
# playing = "#a6e3a1"
# playing_bg = "#1e1e2e"
# highlight = "#cdd6f4"
# highlight_bg = "#628067"
# playing_selected = "#a6e3a1"
# error = "#1e1e2e"
# error_bg = "#f38ba8"
# statusbar = "#a6e3a1"
# statusbar_bg = "#313244"
# statusbar_progress = "#a6e3a1"
# cmdline = "#a6e3a1"
# cmdline_bg = "#181825"

[theme]
background = "#191414"
primary = "#FFFFFF"
secondary = "light black"
title = "#1DB954"
playing = "#1DB954"
playing_selected = "#1ED760"
playing_bg = "#191414"
highlight = "#FFFFFF"
highlight_bg = "#484848"
error = "#FFFFFF"
error_bg = "red"
statusbar = "#191414"
statusbar_progress = "#1DB954"
statusbar_bg = "#1DB954"
cmdline = "#FFFFFF"
cmdline_bg = "#191414"
search_match = "light red"
